#!/bin/sh

### BEGIN INIT INFO
# Provides:          iot_server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to start an IoT Server
### END INIT INFO

. /lib/lsb/init-functions

PROCESS_TITLE="iot_server"
SERVER_PORT=80

start() {
  echo "Starting IoT Server" >&2
  touch /var/lock/subsys/$PROCESS_TITLE
 sudo PORT=$SERVER_PORT PROCESS_NAME=$PROCESS_TITLE node /home/pi/iot/server.js &> /var/log/iot_se
rver.log >&2 iot_server.err.log
}

stop() {
        echo "Stopping IoT Server" >&2
        sudo killall $PROCESS_TITLE
	rm -f /var/lock/subsys/$PROCESS_TITLE
	echo
}


case "$1" in
    start)
        start
	;;
    stop)
	stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status $PROCESS_TITLE
        ;;

    *)
        echo "Usage: /etc/init.d/iot_server start|stop|restart|status"
        exit 1
        ;;
esac

exit 0
